### ISSUE TITLE
TypeError: Cannot read property 'sendUTF' of undefined

### ISSUE THREAD

**Issue by kristapsk** [Dolu89/nostr-proxy#14]
Proxy seems to be working, but it outputs lots of errors like these:
```
Feb 17 14:26:47 106310-h-box node[149621]: TypeError: Cannot read property 'sendUTF' of undefined
Feb 17 14:26:47 106310-h-box node[149621]:     at WebSocket.send (/home/nproxy/nostr-proxy/build/node_modules/.pnpm/websocket-polyfill@0.0.3/node_modules/websocket-polyfill/lib/WebSocket.js:72:30)
Feb 17 14:26:47 106310-h-box node[149621]:     at trySend (/home/nproxy/nostr-proxy/build/node_modules/.pnpm/nostr-tools@1.4.2/node_modules/nostr-tools/lib/nostr.cjs.js:427:10)
Feb 17 14:26:47 106310-h-box node[149621]:     at Object.unsub (/home/nproxy/nostr-proxy/build/node_modules/.pnpm/nostr-tools@1.4.2/node_modules/nostr-tools/lib/nostr.cjs.js:454:9)
Feb 17 14:26:47 106310-h-box node[149621]:     at /home/nproxy/nostr-proxy/build/node_modules/.pnpm/nostr-tools@1.4.2/node_modules/nostr-tools/lib/nostr.cjs.js:627:35
Feb 17 14:26:47 106310-h-box node[149621]:     at Array.forEach (<anonymous>)
Feb 17 14:26:47 106310-h-box node[149621]:     at Object.unsub (/home/nproxy/nostr-proxy/build/node_modules/.pnpm/nostr-tools@1.4.2/node_modules/nostr-tools/lib/nostr.cjs.js:627:14)
Feb 17 14:26:47 106310-h-box node[149621]:     at WebSocket.<anonymous> (/home/nproxy/nostr-proxy/app/Services/NostrSocket.ts:92:62)
Feb 17 14:26:47 106310-h-box node[149621]:     at WebSocket.emit (events.js:400:28)
Feb 17 14:26:47 106310-h-box node[149621]:     at Receiver.receiverOnMessage (/home/nproxy/nostr-proxy/build/node_modules/.pnpm/ws@8.12.1/node_modules/ws/lib/websocket.js:1180:20)
Feb 17 14:26:47 106310-h-box node[149621]:     at Receiver.emit (events.js:400:28)
Feb 17 14:26:47 106310-h-box node[149621]: TypeError: Cannot read property 'sendUTF' of undefined
Feb 17 14:26:47 106310-h-box node[149621]:     at WebSocket.send (/home/nproxy/nostr-proxy/build/node_modules/.pnpm/websocket-polyfill@0.0.3/node_modules/websocket-polyfill/lib/WebSocket.js:72:30)
Feb 17 14:26:47 106310-h-box node[149621]:     at trySend (/home/nproxy/nostr-proxy/build/node_modules/.pnpm/nostr-tools@1.4.2/node_modules/nostr-tools/lib/nostr.cjs.js:427:10)
Feb 17 14:26:47 106310-h-box node[149621]:     at Object.sub (/home/nproxy/nostr-proxy/build/node_modules/.pnpm/nostr-tools@1.4.2/node_modules/nostr-tools/lib/nostr.cjs.js:444:5)
Feb 17 14:26:47 106310-h-box node[149621]:     at /home/nproxy/nostr-proxy/build/node_modules/.pnpm/nostr-tools@1.4.2/node_modules/nostr-tools/lib/nostr.cjs.js:603:17
Feb 17 14:26:47 106310-h-box node[149621]:     at runMicrotasks (<anonymous>)
Feb 17 14:26:47 106310-h-box node[149621]:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
Feb 17 14:26:50 106310-h-box node[149621]: TypeError: Cannot read property 'sendUTF' of undefined
Feb 17 14:26:50 106310-h-box node[149621]:     at WebSocket.send (/home/nproxy/nostr-proxy/build/node_modules/.pnpm/websocket-polyfill@0.0.3/node_modules/websocket-polyfill/lib/WebSocket.js:72:30)
Feb 17 14:26:50 106310-h-box node[149621]:     at trySend (/home/nproxy/nostr-proxy/build/node_modules/.pnpm/nostr-tools@1.4.2/node_modules/nostr-tools/lib/nostr.cjs.js:427:10)
Feb 17 14:26:50 106310-h-box node[149621]:     at Object.unsub (/home/nproxy/nostr-proxy/build/node_modules/.pnpm/nostr-tools@1.4.2/node_modules/nostr-tools/lib/nostr.cjs.js:454:9)
Feb 17 14:26:50 106310-h-box node[149621]:     at /home/nproxy/nostr-proxy/build/node_modules/.pnpm/nostr-tools@1.4.2/node_modules/nostr-tools/lib/nostr.cjs.js:627:35
Feb 17 14:26:50 106310-h-box node[149621]:     at Array.forEach (<anonymous>)
Feb 17 14:26:50 106310-h-box node[149621]:     at Object.unsub (/home/nproxy/nostr-proxy/build/node_modules/.pnpm/nostr-tools@1.4.2/node_modules/nostr-tools/lib/nostr.cjs.js:627:14)
Feb 17 14:26:50 106310-h-box node[149621]:     at WebSocket.<anonymous> (/home/nproxy/nostr-proxy/app/Services/NostrSocket.ts:92:62)
Feb 17 14:26:50 106310-h-box node[149621]:     at WebSocket.emit (events.js:400:28)
Feb 17 14:26:50 106310-h-box node[149621]:     at Receiver.receiverOnMessage (/home/nproxy/nostr-proxy/build/node_modules/.pnpm/ws@8.12.1/node_modules/ws/lib/websocket.js:1180:20)
Feb 17 14:26:50 106310-h-box node[149621]:     at Receiver.emit (events.js:400:28)
Feb 17 14:27:38 106310-h-box node[149621]: TypeError: Cannot read property 'sendUTF' of undefined
Feb 17 14:27:38 106310-h-box node[149621]:     at WebSocket.send (/home/nproxy/nostr-proxy/build/node_modules/.pnpm/websocket-polyfill@0.0.3/node_modules/websocket-polyfill/lib/WebSocket.js:72:30)
Feb 17 14:27:38 106310-h-box node[149621]:     at trySend (/home/nproxy/nostr-proxy/build/node_modules/.pnpm/nostr-tools@1.4.2/node_modules/nostr-tools/lib/nostr.cjs.js:427:10)
Feb 17 14:27:38 106310-h-box node[149621]:     at Object.sub (/home/nproxy/nostr-proxy/build/node_modules/.pnpm/nostr-tools@1.4.2/node_modules/nostr-tools/lib/nostr.cjs.js:444:5)
Feb 17 14:27:38 106310-h-box node[149621]:     at /home/nproxy/nostr-proxy/build/node_modules/.pnpm/nostr-tools@1.4.2/node_modules/nostr-tools/lib/nostr.cjs.js:603:17
Feb 17 14:27:38 106310-h-box node[149621]:     at runMicrotasks (<anonymous>)
Feb 17 14:27:38 106310-h-box node[149621]:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
Feb 17 14:27:38 106310-h-box node[149621]: TypeError: Cannot read property 'sendUTF' of undefined
Feb 17 14:27:38 106310-h-box node[149621]:     at WebSocket.send (/home/nproxy/nostr-proxy/build/node_modules/.pnpm/websocket-polyfill@0.0.3/node_modules/websocket-polyfill/lib/WebSocket.js:72:30)
Feb 17 14:27:38 106310-h-box node[149621]:     at trySend (/home/nproxy/nostr-proxy/build/node_modules/.pnpm/nostr-tools@1.4.2/node_modules/nostr-tools/lib/nostr.cjs.js:427:10)
Feb 17 14:27:38 106310-h-box node[149621]:     at Object.unsub (/home/nproxy/nostr-proxy/build/node_modules/.pnpm/nostr-tools@1.4.2/node_modules/nostr-tools/lib/nostr.cjs.js:454:9)
Feb 17 14:27:38 106310-h-box node[149621]:     at /home/nproxy/nostr-proxy/build/node_modules/.pnpm/nostr-tools@1.4.2/node_modules/nostr-tools/lib/nostr.cjs.js:627:35
Feb 17 14:27:38 106310-h-box node[149621]:     at Array.forEach (<anonymous>)
Feb 17 14:27:38 106310-h-box node[149621]:     at Object.unsub (/home/nproxy/nostr-proxy/build/node_modules/.pnpm/nostr-tools@1.4.2/node_modules/nostr-tools/lib/nostr.cjs.js:627:14)
Feb 17 14:27:38 106310-h-box node[149621]:     at WebSocket.<anonymous> (/home/nproxy/nostr-proxy/app/Services/NostrSocket.ts:92:62)
Feb 17 14:27:38 106310-h-box node[149621]:     at WebSocket.emit (events.js:400:28)
Feb 17 14:27:38 106310-h-box node[149621]:     at Receiver.receiverOnMessage (/home/nproxy/nostr-proxy/build/node_modules/.pnpm/ws@8.12.1/node_modules/ws/lib/websocket.js:1180:20)
Feb 17 14:27:38 106310-h-box node[149621]:     at Receiver.emit (events.js:400:28)
```

**Comment by Dolu89** [comment]
It's related to nostr-tools with nodejs. It's fixed since I'm using my own version of nostr-tools in the `heap` branch
I'm still making some perf. tests in this branch before merging it in `master`
